/**
 * Created by Silen on 2017/7/8.
 */
(function(angular){
    var answer=angular.module('blog_answer',['blog_common','ngRoute']);
    answer.config(['$routeProvider',function($routeProvider){
        $routeProvider.when('/answer',{
            templateUrl:'./answer/answer.html',
            controller:'answerCtrl'
        })
    }])
    answer.controller('answerCtrl',['$scope','$window','$http',function($scope,$window,$http){
       $http({
           url:"../../.././Blog/dist/datas/answerdatas.json",
           method:'get',
       }).then(function(response){
           //默认展示第一页内容
           $scope.result=response.data.data.slice(0,8);
           $scope.$applyAsync();
           //设置分页页数
           var pageNum=response.data.total/response.data.data.slice(0,8).length;
           $scope.page=function(){
               var pageNumArr=[];
               for(var i= 2;i<=pageNum;i++){
                   pageNumArr[pageNumArr.length]=i;
               }
               return pageNumArr;
           }
           $scope.pagenum=$scope.page();
           //设置数字型分页的分页功能
           $scope.pageChange=function(items){
                   $http({
                       url:"../../.././Blog/dist/datas/answerdatas.json",
                       method:'get',
                   }).then(function(response){
                       $scope.result=response.data.data.slice((items-1)*8,items*8);
                       $scope.$applyAsync();
                   })
           }
           //手机屏幕使用的胶囊分页时的分页功能
           $scope.pageindex=1;
           $scope.getPagenext=function(pageindex){
               if(pageindex>pageNum||pageindex<1){
                   return;
               }
               $http({
                   url:"../../.././Blog/dist/datas/answerdatas.json",
                   method:'get',
               }).then(function(response){
                   $scope.result=response.data.data.slice((pageindex-1)*8,pageindex*8);
                   $scope.$applyAsync();
                   $scope.pageindex++;
               })
           }
           $scope.getPageprev=function(pageindex){
               if(pageindex>pageNum||pageindex<1){
                   return;
               }
               $http({
                   url:"../../.././Blog/dist/datas/answerdatas.json",
                   method:'get',
               }).then(function(response){
                   $scope.result=response.data.data.slice((pageindex-1)*8,pageindex*8);
                   $scope.$applyAsync();
                   $scope.pageindex--;
               })
           }
       })
    }])
})(angular)
